export const contractAddress = "0x8945A98c13228D70C323A9dF051Ee785008fcE17";
export const contractAbi = [
    {
        inputs: [
            {internalType: "address", name: "_verifier", type: "address"},
            {internalType: "uint256", name: "_electionId", type: "uint256"},
            {internalType: "bytes32", name: "_merkleRoot", type: "bytes32"},
            {internalType: "uint256", name: "_numCandidates", type: "uint256"},
        ],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "voter",
                type: "address",
            },
            {
                indexed: false,
                internalType: "bytes32",
                name: "commitment",
                type: "bytes32",
            },
        ],
        name: "VoteSubmitted",
        type: "event",
    },
    {
        inputs: [],
        name: "electionId",
        outputs: [{internalType: "uint256", name: "", type: "uint256"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "getElectionInfo",
        outputs: [
            {internalType: "uint256", name: "_electionId", type: "uint256"},
            {internalType: "bytes32", name: "_merkleRoot", type: "bytes32"},
            {internalType: "uint256", name: "_numCandidates", type: "uint256"},
            {internalType: "uint256", name: "_totalVotes", type: "uint256"},
            {internalType: "bool", name: "_votingEnded", type: "bool"},
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "getTotalVotes",
        outputs: [{internalType: "uint256", name: "", type: "uint256"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "getVerifier",
        outputs: [{internalType: "address", name: "", type: "address"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "merkleRoot",
        outputs: [{internalType: "bytes32", name: "", type: "bytes32"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "numCandidates",
        outputs: [{internalType: "uint256", name: "", type: "uint256"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "owner",
        outputs: [{internalType: "address", name: "", type: "address"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {internalType: "uint256[2]", name: "a", type: "uint256[2]"},
            {internalType: "uint256[2][2]", name: "b", type: "uint256[2][2]"},
            {internalType: "uint256[2]", name: "c", type: "uint256[2]"},
            {
                internalType: "uint256[1]",
                name: "publicSignals",
                type: "uint256[1]",
            },
            {internalType: "bytes32", name: "commitment", type: "bytes32"},
        ],
        name: "submitVote",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "totalVotes",
        outputs: [{internalType: "uint256", name: "", type: "uint256"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{internalType: "uint256", name: "_newId", type: "uint256"}],
        name: "updateElectionId",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{internalType: "bytes32", name: "_newRoot", type: "bytes32"}],
        name: "updateMerkleRoot",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {internalType: "uint256", name: "_newRandomness", type: "uint256"},
        ],
        name: "updateRandomness",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{internalType: "uint256", name: "", type: "uint256"}],
        name: "voteCounts",
        outputs: [{internalType: "uint256", name: "", type: "uint256"}],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "votingEnded",
        outputs: [{internalType: "bool", name: "", type: "bool"}],
        stateMutability: "view",
        type: "function",
    },
];
